name: GitHub Actions Demo
run-name: ${{ github.actor }} is testing out GitHub Actions 🚀
on: [push]
workflow_dispatch:
  inputs:
    docker_tag:
      description: "Which image do you want to deploy?"
      required: true
      default: newest
    int:
      type: boolean
      description: "Deploy to INT?"
      required: false
      default: false
    pre:
      type: boolean
      description: "Deploy to PRE?"
      required: false
      default: false
    prod:
      type: boolean
      description: "Deploy to PROD?"
      required: false
      default: false
jobs:
  vars:
    runs-on: ubuntu-latest
    steps:
      - run: echo "$GITHUB_REF_NAME"
      - run: echo "the sha of the commit is ${{ github.sha }}"
      - run: echo "the ref_name is ${{ github.ref_name }}"
      - run: 'echo "shortened_sha=$(echo ${{ github.sha }} | cut -c 1-7)" >> $GITHUB_ENV'
      - run: "echo \"cleaned_ref_name=$(echo ${{ github.ref_name }} | tr '/' '-')\" >> $GITHUB_ENV"
      - run: 'echo "my_tag=${{ env.cleaned_ref_name }}-${{ env.shortened_sha }}" >> $GITHUB_ENV'
      - shell: bash
        run: |
          if test ${{ env.cleaned_ref_name }} = main; then
            echo "on branch main";
          else
            echo "not on branch main";
          fi
      - name: show some variables
        run: |
          echo ${{ env.shortened_sha }}
          echo ${{ env.cleaned_ref_name }}
          echo ${{ env.my_tag }}
          echo ${{ env.blubb }}
      - run: 'echo ${{ env.shortened_sha }}'
      - run: 'echo ${{ env.cleaned_ref_name }}'
      - run: 'echo ${{ env.my_tag }}'
      - run: echo "the whole github env is ${{ toJSON(github) }} !"
