name: GitHub Actions Demo
run-name: ${{ github.actor }} is testing out GitHub Actions 🚀
on: [push]
jobs:
  Explore-GitHub-Actions:
    runs-on: ubuntu-latest
    steps:
      - run: echo "the sha of the commit is ${{ github.sha }}"
      - run: echo "the ref_name is ${{ github.ref_name }}"
      - run: echo "the whole github env is ${{ toJSON(github) }} !"
