name: GitHub Actions Demo
run-name: ${{ github.actor }} is testing out GitHub Actions 🚀
on: [push]
jobs:
  vars:
    runs-on: ubuntu-latest
    steps:
      - run: echo "$GITHUB_REF_NAME"
      - run: echo "the sha of the commit is ${{ github.sha }}"
      - run: echo "the ref_name is ${{ github.ref_name }}"
      - run: 'echo "shortened_sha=$(echo ${{ github.sha }}" | cut -c 1-7) >> $GITHUB_ENV'
      - run: 'echo ${{ env.shortened_sha }}'
      - run: echo "the whole github env is ${{ toJSON(github) }} !"
