name: GitHub Actions Demo
run-name: ${{ github.actor }} is testing out GitHub Actions 🚀
on: [push]
jobs:
  vars:
    runs-on: ubuntu-latest
    steps:
      - run: echo "$GITHUB_REF_NAME"
      - run: echo "the sha of the commit is ${{ github.sha }}"
      - run: echo "the ref_name is ${{ github.ref_name }}"
      - run: 'echo "shortened_sha=$(echo ${{ github.sha }} | cut -c 1-7)" >> $GITHUB_ENV'
      - run: "echo \"cleaned_ref_name=$(echo ${{ github.ref_name }} | tr '/' '-')\" >> $GITHUB_ENV"
      - run: 'echo "my_tag=${{ env.cleaned_ref_name }}-${{ env.shortened_sha }}" >> $GITHUB_ENV'
      - shell: bash
        run: |
          echo "blubb=blubber" >> $GITHUB_ENV
      - name: show some variables
        run: |
          echo ${{ env.shortened_sha }}
          echo ${{ env.cleaned_ref_name }}
          echo ${{ env.my_tag }}
          echo ${{ env.blubb }}
      - run: 'echo ${{ env.shortened_sha }}'
      - run: 'echo ${{ env.cleaned_ref_name }}'
      - run: 'echo ${{ env.my_tag }}'
      - run: echo "the whole github env is ${{ toJSON(github) }} !"
